# Generated by Django 5.2.9 on 2026-01-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('fecha', models.CharField(max_length=20, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('foto_resultado', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alumnos',
                'ordering': ['-created_at'],
            },
        ),
    ]
