# Generated by Django 5.2.9 on 2026-01-16 18:51

import lectorqr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectorqr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['-created_at'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterField(
            model_name='alumno',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=lectorqr.models.ruta_foto_perfil, verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='foto_resultado',
            field=models.ImageField(blank=True, null=True, upload_to=lectorqr.models.ruta_foto_resultado, verbose_name='Foto de resultado'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Alumno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
    ]
