# Generated by Django 5.2.9 on 2026-01-18 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectorqr', '0002_alter_alumno_options_alter_alumno_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Resultado'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')], verbose_name='Teléfono'),
        ),
    ]
