# Generated by Django 5.2.9 on 2026-01-18 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectorqr', '0003_alter_alumno_fecha_alter_alumno_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener el formato 55-4587-4578.', regex='^\\d{2}-\\d{4}-\\d{4}$')], verbose_name='Teléfono'),
        ),
    ]
